services:
  jenkins_agent:
    image: jenkins/ssh-agent:latest-jdk21
    privileged: true
    user: root
    container_name: jenkins_ssh_agent
    restart: always
    ports:
      - "1022:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=tu_wklej_klucz_publiczny_ssh 
